language: node_js
before_script:
- "./node_modules/.bin/bower install"
script:
- "./node_modules/.bin/grunt karma"
- "./node_modules/.bin/grunt lint"
after_script:
- "./node_modules/.bin/grunt coveralls"
cache:
  directories:
  - node_modules
  - app/bower_components
addons:
  sauce_connect: true
env:
  global:
  - secure: bkbxH+K4szuz8OAwzRWbG+iO96y35GnkYJ7K/a6QryucuLj5+PPTqk6YxxhpXVm1cR7ICIMBLKkh/pWhRT1imkUB+VbYPRnZPlEwA4JZ5j/VgPfu+70bbUvrjHrJLhGpl0uNiNR2Lg2uFIF1p6vXyVsUATi4si14z5JGCRkN7sY=
  - secure: JW05o/tUuzL/lY0fKLZfNZaFEvM8nKRxS+JA/Gpr/ouxuK6AqNoitp+269hTi5kKLXMTw0MNY30PVRd/jCtgk+AtTTRDx/6bVB75beHoR5B2GpztJe0i63vfyvIsgyuu4AGwzUVTyqTo/7NNDT/bPAOZVghppyFsqvWRFNWVRaM=
